name: CI
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master
jobs:
  test:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        # python-version: ["3.6", "3.7", "3.8"]
        python-version: ["3.7"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    # container: "python:${{ matrix.python-version }}"
    name: "${{ matrix.os }} Python: ${{ matrix.python-version }}"
    services:
      # redis:
      #   image: redis
      # memcached:
      #   image: memcached:1.6.12-alpine3.14
      # mysql:
      #   image: mysql:8.0.27
      #   ports:
      #     - 3306
      postgresql:
        image: postgres:13.4
        # options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    # - name: Install dependencies
    #   run: |
    #     pip install -U "pip>=21.1"
    #     pip install -U setuptools
    #     pip install -U "tox>=3.23.0,<4" codecov tox-gh-actions coverage
    - name: Log python & pip versions
      run: |
        python --version
        pip --version
    # - name: Install db clients
    #   run: |
    #     apt-get update
    #     apt-get install -y  mariadb-client-10.5 postgresql-client-13
    - name: prep DB
      env:
        MYSQL_TCP_PORT: 3306
        MYSQL_HOST: mysql
        PGHOST: 127.0.0.1
        PGPORT: 5432
      run: |
        psql -U postgres -c 'CREATE DATABASE postgis'
        psql -U postgres postgis -c 'CREATE EXTENSION IF NOT EXISTS postgis;'
        mysql -e 'create database django_prometheus_1;'
    - name: Run unit tests
      run: tox
